version: 2
updates:
  - package-ecosystem: "composer"
    open-pull-requests-limit: 8
    directory: "/"
    schedule:
        interval: "daily"
    env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
