version: 2
updates:
  - package-ecosystem: "composer"
    open-pull-requests-limit: 4
    directory: "/"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    schedule:
        interval: "daily"
    env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
